name: CI
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    if: contains(github.event.commits[0].message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: bahmutov/npm-install@v1.1.0

      - run: npm run eslint

  unit-tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      # checkout + npm install
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: bahmutov/npm-install@v1.1.0

      # install Roblox Studio
      - run: pip install wget psutil
      - run: python tests/scripts/install.py "${{ secrets.ROBLOSECURITY }}"

      # install rojo + run-in-roblox
      - uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: foreman install

      # compile and run tests
      - run: npm test

  typedoc:
    name: Typedoc Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - uses: bahmutov/npm-install@v1

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Generate Documentation
        run: npm run typedoc

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          GIT_CONFIG_NAME: "GitHub Actions"
          GIT_CONFIG_EMAIL: "noreply@github.com"
