name: Documentation
on: [push]

jobs:
  typedoc:
    name: Typedoc Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with: 
          node-version: 14.x

      - run: npm install
      - run: npm run typedoc

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
